### ISSUE TITLE
Return Polars DF

### ISSUE THREAD

**Issue by dmi3kno** [ilnaes/tidytuesdayPy#2]
Did you consider supporting polars format as well? I am teaching a course on polars and plan to use your package to fetch data. Of course I can `pl.from_pandas(tt.data["id"])`, but I think it would be useful going forward if you had some nice wrappers, for example:
```{python}
from tidytuesday import TidyTuesday
tt= TidyTuesday("2024-05-21")

em1 = tt.to_pandasDF('emissions')
em2 = tt.to_polarsDF('emissions')

## or maybe even
tt.to_parquet('emissions', 'tt_emissions.parquet')
tt.to_csv('emissions', 'tt_emissions.csv')

```

**Comment by ilnaes** [comment]
I haven't been keeping up with things recently, so I haven't used polars, and I didn't even know about it when I wrote the package. The read/write functions look similar enough that it probably wouldn't be a big deal to implement.

If I add polars directly, that would add a dependency. On the other hand, since the interfaces between pandas and polars are so similar, I think I could do something like let TidyTuesday take a module as an optional argument with pandas being the default. You could then just pass the polars module. So something like

```
import polars as pl
tt = TidyTuesday("2024-05-21", mod=pl)

em = tt.data["emissions"] # is in polars form
```

Would that sound good?

**Comment by dmi3kno** [comment]
that sounds fantastic. Thank you!

**Comment by ilnaes** [comment]
I've updated the package here 9f672869747b0495f020dc81ced7428c4362104a and on Pypi.

There's an option to add kwargs (as detailed in the readme) in case of any weirdness with future data formats, but it should work for normal csv's out of the box.

If you run into any issues, let me know!
